CREATE TABLE IF NOT EXISTS Album (
id SERIAL PRIMARY KEY,
album_title VARCHAR(130) UNIQUE NOT NULL,
year INTEGER NOT NULL
);  

CREATE TABLE IF NOT EXISTS Track (
id SERIAL PRIMARY KEY,
album_title VARCHAR(130) UNIQUE NOT NULL PRIMARY KEY REFERENCES Album(id),
name VARCHAR(60) UNIQUE NOT NULL,
time NUMERIC NOT NULL
);  

CREATE TABLE IF NOT EXISTS Collection (
id SERIAL PRIMARY KEY,
year INTEGER NOT NULL
);  

CREATE TABLE IF NOT EXISTS Genre (
id SERIAL PRIMARY KEY,
title VARCHAR(100) UNIQUE NOT NULL
);  

CREATE TABLE IF NOT EXISTS Singer (
id SERIAL PRIMARY KEY,
name VARCHAR(120) UNIQUE NOT NULL
);  

CREATE TABLE IF NOT EXISTS GenreSinger (
genre_id INTEGER REFERENCES Genre(id),
singer_id INTEGER REFERENCES Singer(id),
CONSTRAINT k PRIMARY KEY (genre_id, singer_id)
);  

CREATE TABLE IF NOT EXISTS SingerAlbum (
album_id INTEGER REFERENCES Album(id),
singer_id INTEGER REFERENCES Singer(id),
CONSTRAINT k1 PRIMARY KEY (album_id, singer_id)
);  

CREATE TABLE IF NOT EXISTS TrackCollection (
track_id INTEGER REFERENCES Track(id),
collection_id INTEGER REFERENCES Collection(id),
CONSTRAINT k2 PRIMARY KEY (track_id, collection_id)
);  

